export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_GOOGLE_AUTH_REQUEST = "USER_GOOGLE_AUTH_REQUEST";
export const USER_GOOGLE_AUTH_SUCCESS = "USER_GOOGLE_AUTH_SUCCESS";
export const USER_GOOGLE_AUTH_ERROR = "USER_GOOGLE_AUTH_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
